from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session, joinedload
from .. import models, schemas
from ..database import get_db


router = APIRouter(prefix="/expenses", tags=["Expenses"])


@router.post("/", response_model=schemas.TransactionResponse)
def create_transaction(transaction: schemas.TransactionCreate, db: Session = Depends(get_db)):
    # 1. Create the Header
    db_header = models.TransactionHeader(
        payer_user_id=transaction.payer_user_id,
        store_id=transaction.store_id,
        payment_mode_id=transaction.payment_mode_id,
        trxn_date=transaction.trxn_date,
        total_amount=transaction.total_amount,
        currency=transaction.currency,
        source_type=transaction.source_type,
        source_reference=transaction.source_reference,
        is_reconciled=transaction.is_reconciled
    )
    db.add(db_header)
    db.flush() # Flush to get the trxn_id generated by the model

    # 2. Handle Global Splits (Header Level)
    for split_data in transaction.splits:
        db_split = models.ExpenseSplit(
            trxn_id=db_header.trxn_id, # Link to Header
            debtor_id=split_data.debtor_id,
            owned_amount=split_data.owned_amount,
            currency=split_data.currency,
            is_settled=split_data.is_settled
        )
        db.add(db_split)

    # 3. Handle Lines & Line Splits
    for line_data in transaction.lines:
        db_line = models.TransactionLine(
            trxn_id=db_header.trxn_id, # Link to Header
            product_id=line_data.product_id,
            product_name=line_data.product_name,
            quantity=line_data.quantity,
            metric=line_data.metric,
            unit_price=line_data.unit_price,
            line_amount=line_data.line_amount
        )
        db.add(db_line)
        db.flush() # Flush to get the line_id

        # Handle Splits specific to this Line
        for line_split_data in line_data.splits:
            db_line_split = models.ExpenseSplit(
                line_id=db_line.line_id, # Link to Line
                debtor_id=line_split_data.debtor_id,
                owned_amount=line_split_data.owned_amount,
                currency=line_split_data.currency,
                is_settled=line_split_data.is_settled
            )
            db.add(db_line_split)

    db.commit()
    db.refresh(db_header)
    return db_header


@router.get("/", response_model=list[schemas.TransactionResponse])
def read_transactions(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    # We use joinedload to fetch lines and splits in a single efficient query
    transactions = db.query(models.TransactionHeader)\
        .options(joinedload(models.TransactionHeader.lines).joinedload(models.TransactionLine.splits))\
        .options(joinedload(models.TransactionHeader.splits))\
        .offset(skip).limit(limit).all()
    return transactions