from app.models import engine, User
from sqlalchemy.orm import sessionmaker

# 1. Setup the session
Session = sessionmaker(bind=engine)
session = Session()

def create_new_user(username: str, email: str, contact_number: str, firstname: str =  None, lastname: str = None, default_currency: str = "GBP"):
    """
    Creates a new user and commits to the database.
    The user_id is auto-generated by the model's 'generate_id' function.
    """
    try:
        # 2. Create the User object
        # Note: We do not need to pass user_id, it is generated automatically via the prefix function
        new_user = User(
            username=username,
            email=email,
            firstname=firstname,  # OPTIONAL: You can choose to make this nullable in the model if you want
            lastname=lastname,  # OPTIONAL: You can choose to make this nullable in the model if you want
            contact_number=contact_number,
            default_currency=default_currency,
            is_active=True
        )

        # 3. Add and Commit
        session.add(new_user)
        session.commit()
        
        # 4. Refresh to get the generated ID back from the DB (optional but good practice)
        session.refresh(new_user)

        print(f"✅ User created successfully!")
        print(f"ID:       {new_user.user_id}")
        print(f"Username:     {new_user.username}")
        print(f"Email:        {new_user.email}")
        print(f"First Name:   {new_user.firstname}")
        print(f"Last Name:    {new_user.lastname}")
        print(f"Contact Number: {new_user.contact_number}")
        print(f"Currency: {new_user.default_currency}")
        
        return new_user

    except Exception as e:
        session.rollback()
        print(f"❌ Error creating user: {e}")
    finally:
        session.close()

if __name__ == "__main__":
    # Example usage:
    # You can change these values or add input() prompts
    create_new_user(
        username="cos(t)", 
        email="ksstubh.sonawane@gmail.com",
        firstname="Kaustubh",
        lastname="Sonawane",
        contact_number="+447388229743",
        default_currency="GBP"
    )